inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-rspec_rails

# 自動生成されるものなどはチェック対象から除外する
AllCops:
  Exclude:
    - "bin/*"
    - "config/application.rb"
    - "config/backup.rb"
    - "config/boot.rb"
    - "config/environments/*"
    - "config/unicorn.rb"
    - "config/spring.rb"
    - "config/puma.rb"
    - "config.ru"
    - "db/**/*"
    - "deploy/*"
    - "node_modules/**/*"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"
    - "vendor/**/*"
  NewCops: enable

# ============================================================
# Style
# ============================================================
# 日本語コメントを許可
# https://docs.rubocop.org/rubocop/cops_style.html#styleasciicomments
Style/AsciiComments:
  Enabled: false

# ドキュメントの無い public class を許可する
# https://docs.rubocop.org/rubocop/cops_style.html#styledocumentation
Style/Documentation:
  Enabled: false

# https://docs.rubocop.org/rubocop/cops_style.html#stylefrozenstringliteralcomment
Style/FrozenStringLiteralComment:
  Enabled: false

# ネストしたクラスの書き方を許可
Style/ClassAndModuleChildren:
  Enabled: false

# 行の最大長をチェックしない
Layout/LineLength:
  Enabled: false

# ロケールファイルへのエラーメッセージの強制を無効にする
Rails/I18nLocaleTexts:
  Enabled: false

# メソッドの行数に対する制限を無効にする
Metrics/MethodLength:
  Enabled: false

# テストタイプの推論を無効にする
RSpecRails/InferredSpecType:
  Enabled: false
