inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-capybara

# 自動生成されるものなどはチェック対象から除外する
AllCops:
  Exclude:
    - "bin/*"
    - "config/application.rb"
    - "config/backup.rb"
    - "config/boot.rb"
    - "config/environments/*"
    - "config/unicorn.rb"
    - "config/spring.rb"
    - "config/puma.rb"
    - "config.ru"
    - "db/*schema.rb"
    - "deploy/*"
    - "node_modules/**/*"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"
    - "vendor/**/*"
  NewCops: enable
