inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-rspec_rails

# 自動生成されるものなどはチェック対象から除外する
AllCops:
  Exclude:
    - "bin/*"
    - "config/application.rb"
    - "config/backup.rb"
    - "config/boot.rb"
    - "config/environments/*"
    - "config/unicorn.rb"
    - "config/spring.rb"
    - "config/puma.rb"
    - "config.ru"
    - "db/*schema.rb"
    - "deploy/*"
    - "node_modules/**/*"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"
    - "vendor/**/*"
  NewCops: enable

# ============================================================
# Style
# ============================================================
# 日本語コメントを許可
# https://docs.rubocop.org/rubocop/cops_style.html#styleasciicomments
Style/AsciiComments:
  Enabled: false

# ドキュメントの無い public class を許可する
# https://docs.rubocop.org/rubocop/cops_style.html#styledocumentation
Style/Documentation:
  Enabled: false

# https://docs.rubocop.org/rubocop/cops_style.html#stylefrozenstringliteralcomment
Style/FrozenStringLiteralComment:
  Enabled: false
  
# namespace 付きのクラスは簡単に書きたい。
# https://docs.rubocop.org/rubocop/cops_style.html#styleclassandmodulechildren
Style/ClassAndModuleChildren:
  Enabled: false

# ============================================================
# Metrics
# ============================================================

# 30 ぐらいまでは許容してもいいのでは
# https://docs.rubocop.org/rubocop/cops_metrics.html#metricsabcsize
Metrics/AbcSize:
  Max: 30

# 20くらいは別によいと思う
# https://docs.rubocop.org/rubocop/cops_metrics.html#metricsmethodlength
Metrics/MethodLength:
  Max: 20