services:
  app:
    build:
      context: .
      dockerfile: ../infra/stg/app/Dockerfile
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    volumes:
      - ./:/E-Commerce-Webapp-with-Stripe-Sync
    environment:
      RAILS_ENV: staging
      TZ: Asia/Tokyo
    user: root
    env_file:
      - .env

  web:
    build:
      context: ../infra/stg/web
    depends_on:
      - app
    volumes:
      - ../infra/stg/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/E-Commerce-Webapp-with-Stripe-Sync/public
      - ./tmp:/E-Commerce-Webapp-with-Stripe-Sync/tmp

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: 'art-sa2-stg.com -> http://web:80'
      STAGE: "production"
    volumes:
      - https-portal-data:/var/lib/https-portal

volumes:
  https-portal-data: # HTTPS-PORTALをアップグレードする際に再署名を避けるために推奨されます
