services:
  app:
    build:
      context: .
    image: artsa2shop/art-sa2-shop-prod:app-latest
    volumes:
      - ./:/E-Commerce-Webapp-with-Stripe-Sync
    environment:
      RAILS_ENV: production
      TZ: Asia/Tokyo
    user: root
    env_file:
      - .env

  web:
    image: artsa2shop/art-sa2-shop-prod:web-latest
    depends_on:
      - app
    volumes:
      - ../infra/prod2/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/E-Commerce-Webapp-with-Stripe-Sync/public

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: "art-sa2.com -> http://web:80"
      STAGE: "production"
    volumes:
      - https-portal-data:/var/lib/https-portal

volumes:
  # public-data:
  # tmp-data:
  https-portal-data: # HTTPS-PORTALをアップグレードする際に再署名を避けるために推奨されます
