services:
  app:
    image: artsa2/art-sa2-shop:app-latest
    volumes:
      - ./:/E-Commerce-Webapp-with-Stripe-Sync
      - /E-Commerce-Webapp-with-Stripe-Sync/tmp/sockets:/E-Commerce-Webapp-with-Stripe-Sync/tmp/sockets
    environment:
      RAILS_ENV: production
      TZ: Asia/Tokyo
    user: root
    env_file:
      - .env

  web:
    image: artsa2/art-sa2-shop:web-latest
    depends_on:
      - app
    volumes:
      - ../infra/prod/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/E-Commerce-Webapp-with-Stripe-Sync/public
      - /E-Commerce-Webapp-with-Stripe-Sync/tmp/sockets:/E-Commerce-Webapp-with-Stripe-Sync/tmp/sockets

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: "art-sa2-stg.com -> http://web:80"
      STAGE: "production"
      CLIENT_MAX_BODY_SIZE: 100M
      WEBSOCKET: "true"
    volumes:
      - https-portal-data:/var/lib/https-portal

volumes:
  https-portal-data: # HTTPS-PORTALをアップグレードする際に再署名を避けるために推奨されます
