services:
  app:
    image: artsa2/art-sa2-shop:app-latest
    volumes:
      - public-data:/src/public
      - tmp-data:/src/tmp
    environment:
      RAILS_ENV: production
      TZ: Asia/Tokyo
    user: root
    env_file:
      - .env

  web:
    image: artsa2/art-sa2-shop:web-latest
    depends_on:
      - app
    volumes:
      - ../infra/prod/web/default.conf:/etc/nginx/conf.d/default.conf
      - public-data:/src/public
      - tmp-data:/src/tmp

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: "art-sa2.com -> http://web:80"
      STAGE: "production"
    volumes:
      - https-portal-data:/var/lib/https-portal

volumes:
  public-data:
  tmp-data:
  https-portal-data: # HTTPS-PORTALをアップグレードする際に再署名を避けるために推奨されます
