const defaultTheme = require("tailwindcss/defaultTheme");

module.exports = {
  darkMode: "class",
  content: [
    "./public/*.html",
    "./app/helpers/*.rb",
    "./app/javascript/**/*.js",
    "./app/views/**/*",
    "./node_modules/flowbite/**/*.js",
  ],
  safelist: [
    "flex",
    "flex-row-reverse",
    "items-start",
    "gap-2.5",
    "w-full",
    "max-w-[320px]",
    "flex-col",
    "gap-1",
    "leading-1.5",
    "rounded-s-xl",
    "rounded-se-xl",
    "bg-sky-400",
    "p-4",
    "text-sm",
    "font-normal",
    "text-white",
    "rounded-e-xl",
    "rounded-ss-xl",
    "border-gray-200",
    "bg-gray-200",
    "text-gray-900",
    "text-gray-400",
    "inline-flex",
    "self-center",
    "rounded-full",
    "p-2",
    "text-center",
    "hover:bg-sky-100",
    "z-10",
    "hidden",
    "w-40",
    "divide-y",
    "divide-gray-100",
    "rounded-lg",
    "bg-white",
    "shadow-xl",
    "py-2",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter var", ...defaultTheme.fontFamily.sans],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/aspect-ratio"),
    require("@tailwindcss/typography"),
    require("@tailwindcss/container-queries"),
    require("flowbite/plugin"),
  ],
};
