name: CI TEST
run-name: ${{ github.actor }} is CI testing
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        MYSQL_ROOT_DATABASE: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
    
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build and run containers
        run: docker compose -f src/compose.yml up --build -d

      - name: run lint
        run: docker compose -f src/compose.yml exec app yarn lint:fix
    
      - name: run rubocop
        run: docker compose -f src/compose.yml exec app bundle exec rubocop

      - name: run rspec
        run: docker compose -f src/compose.yml exec app bundle exec rspec

      - name: shutdown
        run: docker compose -f src/compose.yml down

#   deploy-to-production:
#     needs: build-and-test
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main' && github.event_name == 'push'

#     steps:
#       - name: Check
#         uses: actions/checkout@v4

#       - name: Deploy
#         run: |
#           echo "${{ secrets.PRIVATE_KEY }}" > private_key
#           chmod 600 private_key
#           ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=2 ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }} -i private_key "\
#           cd /home/ubuntu/web/E-Commerce-Webapp-with-Stripe-Sync && \
#           git fetch git@github.com:seiichikick0404/E-Commerce-Webapp-with-Stripe-Sync.git && \
#           git pull git@github.com:seiichikick0404/E-Commerce-Webapp-with-Stripe-Sync.git && \
#           docker compose -f compose.prod.yml down && \
#           docker compose -f compose.prod.yml build && \
#           docker compose -f compose.prod.yml up -d && \
#           docker compose -f compose.prod.yml run app rails db:create && \
#           docker compose -f compose.prod.yml run app rails db:migrate"