# 本番環境の準備が整うまでコメントアウト

# name: CI TEST
# run-name: ${{ github.actor }} is CI testing
# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: checkout
#         uses: actions/checkout@v4

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: build and Run containers
#         shell: bash
#         run: docker compose up --build -d
#         env:
#           MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
#           SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}

#       - name: Run compose ps
#         shell: bash
#         run: docker compose -f compose.yml ps
#         env:
#           MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
#           SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}

#       - name: setup db
#         shell: bash
#         env:
#           MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
#           SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
#         run: |
#           docker compose -f compose.yml run wait db:3306 -- echo "Database is up"
#           docker compose exec -T app rails db:create
#           docker compose exec -T app rails db:migrate

#       - name: run test
#         shell: bash
#         run: |
#           docker compose exec -T app rails test
#         env:
#           MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

#       - name: Shutdown
#         run: docker compose down

#   deploy-to-production:
#     needs: build-and-test
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main' && github.event_name == 'push'

#     steps:
#       - name: Check
#         uses: actions/checkout@v4

#       - name: Deploy
#         run: |
#           echo "${{ secrets.PRIVATE_KEY }}" > private_key
#           chmod 600 private_key
#           ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=2 ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }} -i private_key "\
#           cd /home/ubuntu/web/E-Commerce-Webapp-with-Stripe-Sync && \
#           git fetch git@github.com:seiichikick0404/E-Commerce-Webapp-with-Stripe-Sync.git && \
#           git pull git@github.com:seiichikick0404/E-Commerce-Webapp-with-Stripe-Sync.git && \
#           docker compose -f compose.prod.yml down && \
#           docker compose -f compose.prod.yml build && \
#           docker compose -f compose.prod.yml up -d && \
#           docker compose -f compose.prod.yml run app rails db:create && \
#           docker compose -f compose.prod.yml run app rails db:migrate"
